apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-amd64
spec:
  replicas: 5
  selector:
    matchLabels:
      app: workload-amd64
  template:
    metadata:
      labels:
        app: workload-amd64
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: pause
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1